### ISSUE TITLE
Start checkin Failed

### ISSUE THREAD

**Issue by Oraer** [Alluofuyo/cordcloud_checkin#4]
作者您好，我fork了您的项目，按照您推荐的方法在Actions中部署，但是我遇到了一些问题 Start checkin Failed，

您能告诉我我是哪一步出了问题吗？我将感激不尽！

当我在 workflow 中运行 test 时发生了如下报错 Start checkin Failed：

```
Permission denied: './chromedriver/chromedriver-linux64/chromedriver

selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.
```

完整报错如下：

```
Run export DISPLAY=:99
[1]+  1773 Running                 sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
Traceback (most recent call last):
google chrome version: 115.0.5790.102
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 206, in _start_process
    self.process = subprocess.Popen(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/subprocess.py", line 971, in __init__
major version is 115
{'timestamp': '2023-08-01T18:09:01.353Z', 'channels': {'Stable': {'channel': 'Stable', 'version': '115.0.5790.102', 'revision': '1148114', 'downloads': {'chrome': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chrome-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-arm64/chrome-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-x64/chrome-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/win32/chrome-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/win64/chrome-win64.zip'}], 'chromedriver': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chromedriver-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-arm64/chromedriver-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-x64/chromedriver-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/win32/chromedriver-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/win64/chromedriver-win64.zip'}]}}, 'Beta': {'channel': 'Beta', 'version': '116.0.5845.49', 'revision': '1160321', 'downloads': {'chrome': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/linux64/chrome-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/mac-arm64/chrome-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/mac-x64/chrome-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/win32/chrome-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/win64/chrome-win64.zip'}], 'chromedriver': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/linux64/chromedriver-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/mac-arm64/chromedriver-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/mac-x64/chromedriver-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/win32/chromedriver-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.49/win64/chromedriver-win64.zip'}]}}, 'Dev': {'channel': 'Dev', 'version': '117.0.5911.2', 'revision': '1175078', 'downloads': {'chrome': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/linux64/chrome-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/mac-arm64/chrome-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/mac-x64/chrome-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/win32/chrome-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/win64/chrome-win64.zip'}], 'chromedriver': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/linux64/chromedriver-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/mac-arm64/chromedriver-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/mac-x64/chromedriver-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/win32/chromedriver-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5911.2/win64/chromedriver-win64.zip'}]}}, 'Canary': {'channel': 'Canary', 'version': '117.0.5923.0', 'revision': '1177453', 'downloads': {'chrome': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/linux64/chrome-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/mac-arm64/chrome-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/mac-x64/chrome-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/win32/chrome-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/win64/chrome-win64.zip'}], 'chromedriver': [{'platform': 'linux64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/linux64/chromedriver-linux64.zip'}, {'platform': 'mac-arm64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/mac-arm64/chromedriver-mac-arm64.zip'}, {'platform': 'mac-x64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/mac-x64/chromedriver-mac-x64.zip'}, {'platform': 'win32', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/win32/chromedriver-win32.zip'}, {'platform': 'win64', 'url': 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5923.0/win64/chromedriver-win64.zip'}]}}}}
download chrome driver successfully.
unzip chromedriver to ./chromedriver-linux64/chromedriver
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno [13](https://github.com/Oraer/cordcloud_checkin/actions/runs/5734475090/job/15540714503#step:7:14)] Permission denied: './chromedriver/chromedriver-linux64/chromedriver'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cordcloud_checkin/cordcloud_checkin/AutoCheckin.py", line 192, in <module>
    main()
  File "/home/runner/work/cordcloud_checkin/cordcloud_checkin/AutoCheckin.py", line [18](https://github.com/Oraer/cordcloud_checkin/actions/runs/5734475090/job/15540714503#step:7:19)8, in main
    start_checkin(username, password, url, chrome_path, chromedriver_path)
  File "/home/runner/work/cordcloud_checkin/cordcloud_checkin/AutoCheckin.py", line 1[19](https://github.com/Oraer/cordcloud_checkin/actions/runs/5734475090/job/15540714503#step:7:20), in start_checkin
    driver = uc.Chrome(options=options, driver_executable_path=chromedriver_path)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 105, in start
    self._start_process(self._path)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 2[21](https://github.com/Oraer/cordcloud_checkin/actions/runs/5734475090/job/15540714503#step:7:22), in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.

Error: Process completed with exit code 1.
```

**Comment by Alluofuyo** [comment]
非常感谢你的问题描述，这个问题是由chromedriver的执行和写入权限导致的，python进行unzip解压时不会保留文件的unix权限，所以需要额外进行提权操作，目前已经解决这个问题了，你同步仓库过去即可。
